nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: https://github.com/pei0804
  HatenaBlog: http://tikasan.hatenablog.com

projects_url: https://github.com/pei0804

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/pei0804
        twitter: https://twitter.com/pei0804
        facebook: https://www.facebook.com/profile.php?id=100006322935889
    show_all_posts: false
    post_count: 20
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
